DROP TABLE IF EXISTS Teacher;

CREATE TABLE IF NOT EXISTS Teacher (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    teacherEmail VARCHAR(254) NOT NULL,
    teacherName VARCHAR(70) NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (teacherEmail)
);
