DROP TABLE IF EXISTS Student;

CREATE TABLE IF NOT EXISTS Student (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    studentEmail VARCHAR(254) NOT NULL,
    studentName VARCHAR(70) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (studentEmail)
);
