DROP TABLE IF EXISTS Student;

CREATE TABLE IF NOT EXISTS Student (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    studentEmail VARCHAR(254) NOT NULL,
    studentName VARCHAR(70),
    dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateModified TIMESTAMP NOT NULL
);
