DROP TABLE IF EXISTS Class;

CREATE TABLE IF NOT EXISTS Class (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    classCode VARCHAR(10) NOT NULL,
    className VARCHAR(50) NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (classCode)
);
