DROP TABLE IF EXISTS Subject;

CREATE TABLE IF NOT EXISTS Subject (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    subjectCode VARCHAR(10) NOT NULL,
    subjectName VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (subjectCode)
);
